language: rust
rust:
  - nightly
  - beta
  - stable
cache: cargo
install:
  - sudo apt-get -qq update
  - sudo apt-get install youtube-dl
matrix:
  allow_failures:
    - rust:
        - beta
        - stable
  fast_finish: true
